version: '3.8'

services:
  app:
    build: .
    image: devsu_test:latest
    container_name: devsu_app

    # Mapea el puerto (usa 8000 por defecto, o el que pongas en .env)
    ports:
      - "${PORT:-8000}:8000"

    # Carga las vars de tu .env
    env_file:
      - .env

    # Volumen para persistir SQLite
    volumes:
      - ./dev.sqlite:/usr/src/app/dev.sqlite
    user: root
    # Reinicia hasta 3 veces si falla el contenedor
    restart: "on-failure:3"

    # Healthcheck
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${PORT:-8000}/api/users || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
